num_str = input('Input a number: ')
num_int = int(num_str)
num_hex = hex(num_int)
num_oct = oct(num_int)
num_bin = bin(num_int)

print('Decimal:', num_int)
print('Hexadecimal:', num_hex)
print('Octal:', num_oct)
print('Binary:', num_bin)